CREATE TABLE  orders 
(
   ACTReportInfo2 varchar(13),
   AESInstanceID int,
   AESMVDSequenceStatus int,
   AESOMInstanceID int,
   AESOMOrderID int,
   AESOMParentOrderID varchar(20),
   AESOMRoutingDest varchar(21),
   AESOrderGeneratorID varchar(12),
   AESOrderInternalState varchar(3),
   AESPauseCode int,
   AESRoutingRestrictions int,
   Account varchar(14),
   AccountType varchar(6),
   AccruedInterest NUMERIC(19,8),
   AdditionalFee NUMERIC(19,8),
   AdjustTktPrice int,
   AllOrNone int,
   AllocQuantity NUMERIC(19,2),
   Anonymous int,
   ArrivalPrice NUMERIC(19,8),
   AsOfTimestamp timestamp,
   AutoAllocate int,
   AutoBookExternalAccount varchar(14),
   AutoBookInternalAccount varchar(14),
   AutoConfirmation int,
   AutoTrade varchar(2),
   AverageFXRate NUMERIC(19,8),
   AveragePrice NUMERIC(19,8),
   AvgFXForwardPoints NUMERIC(19,2),
   BackCancelCorrect varchar(1),
   BackOfficeOrderID int,
   BackOfficeSystem varchar(8),
   BackOfficeTactic varchar(9),
   BargainTermCode varchar(1),
   BaseCurrency varchar(4),
   BasketLegID varchar(21),
   BasketType varchar(9),
   BlockTradeBrokerKey varchar(20),
   BlockTradeReportCode int,
   BookingEntity varchar(10),
   BookingSecurityID varchar(27),
   BookingSecurityIDSource varchar(9),
   BranchSeqNumber varchar(25),
   BulletinBoardSize int,
   CancelState varchar(7),
   ChangedTimestamp timestamp,
   CheckedCashValue NUMERIC(19,8),
   CheckedClientAccount varchar(15),
   CheckedGroupID varchar(15),
   CheckedNetSell NUMERIC(19,8),
   ClearingInstructions varchar(9),
   ClientID varchar(14),
   ClientLocation varchar(5),
   ClientOrderID varchar(40),
   ClientPortfolioID varchar(11),
   ClientSecurityID varchar(26),
   ClientSecurityIDSource varchar(9),
   Commission varchar(24),
   CommissionType varchar(1),
   CompressParameter int,
   CompressTimeout int,
   ConnectionID varchar(20),
   ControllingUser varchar(14),
   Coupon NUMERIC(19,8),
   CrossInstructions int,
   CrossInternalPrice NUMERIC(19,8),
   CumulativeQuantity NUMERIC(19,2),
   CurrentMarker int,
   CustomerAccount varchar(14),
   DayCumulativeQuantity NUMERIC(19,2),
   DefaultDestination varchar(27),
   DeliveryType varchar(9),
   DestinationAccountType varchar(6),
   DestinationDesk varchar(10),
   DestinationRegionCode varchar(5),
   DestinationServiceMessage varchar(75),
   DestinationServiceName varchar(15),
   DestinationServiceOrderID varchar(25),
   DestinationServiceSeqNum int,
   DestinationUser varchar(14),
   DestinationUserCC varchar(14),
   Discretion int,
   DividendAdjustment varchar(3),
   ExTriggerActivationStatus int,
   Exchange varchar(13),
   ExchangeRate NUMERIC(19,8),
   ExchangeTag varchar(20),
   ExchangeTradeDate timestamp,
   ExecutionAlgo varchar(49),
   ExecutionCapacity varchar(16),
   ExecutionMode varchar(9),
   ExecutionPrice NUMERIC(19,8),
   ExecutionTrigger varchar(75),
   ExternalClientOrderID varchar(36),
   FIXSessionID varchar(60),
   FOBOOrderTradeID varchar(25),
   FXAveragePriceAllIn NUMERIC(19,8),
   FXCcy2 int,
   FXCumulativeQuantityBaseCcy NUMERIC(19,2),
   FXCumulativeQuantityLocalCcy NUMERIC(19,2),
   FXFwSwFarLegSettlement varchar(10),
   FXFwSwNearLegSettlement varchar(10),
   FXFwSwQuoteID varchar(50),
   FXFwdBookingStatus int,
   FXFwdInstructions int,
   FXLocalCcyRate NUMERIC(19,8),
   FXQuantityLocalCcy NUMERIC(19,2),
   FXRate NUMERIC(19,8),
   GiveUp varchar(9),
   IOI int,
   InstanceID varchar(1),
   IntermarketSweep varchar(1),
   InternalCrossEligible varchar(1),
   InternalIOI int,
   InternalIOIPrice NUMERIC(19,8),
   InternalIOIQuantity int,
   InvestorID varchar(36),
   JitneyBrokerCode varchar(3),
   LastUser varchar(14),
   LatestFXForwardPoints NUMERIC(19,8),
   LeavesQuantity NUMERIC(19,2),
   LocalTaxes NUMERIC(19,8),
   LocateBrokerID varchar(27),
   LocateProvided varchar(3),
   LocatedShares NUMERIC(19,2),
   MLID varchar(16),
   MLLegNumber int,
   MLParentID varchar(16),
   MLParentLegNumber int,
   MLParentTotalLegs int,
   MLTotalLegs int,
   MarketHeld int,
   MarkupPrice NUMERIC(19,8),
   MaturityDate varchar(10),
   MaxShow NUMERIC(19,2),
   Memo varchar(75),
   MifidRouting varchar(2),
   MifidShowLmt int,
   MifidTktQuantity int,
   MinAcceptableQuantity NUMERIC(19,2),
   MinCommission NUMERIC(19,8),
   NYSERule92Terms varchar(24),
   NothingDoneFlag int,
   OpenCloseIndicator varchar(8),
   OrderBookingState varchar(7),
   OrderEntryType varchar(1),
   OrderID varchar(16) NOT NULL,
   OrderOriginatorRegionCode varchar(5),
   OrderReceiptTimestamp timestamp,
   OrderTimestamp timestamp,
   PAdjustTktPrice int,
   PClientOrderID varchar(40),
   PExecutionAlgo varchar(49),
   PExecutionMode varchar(9),
   PExecutionTrigger varchar(75),
   PExternalClientOrderID varchar(36),
   PFXQuantityLocalCcy NUMERIC(19,2),
   PMarketHeld int,
   PMaxShow NUMERIC(19,2),
   PMemo varchar(75),
   PPriceInstruction varchar(32),
   PQuantity NUMERIC(19,2),
   PQuoteSize NUMERIC(19,8),
   PSSExemptCode int,
   PSide varchar(4),
   PTMLevy NUMERIC(19,8),
   PTimeInForce varchar(14),
   PairsMaxLegQuantity NUMERIC(19,2),
   Bid NUMERIC(19,8),
   Ask NUMERIC(19,8),
   PairsStopLossAmount NUMERIC(19,8),
   ParentOrderID varchar(16),
   Precision int,
   PriceInstruction varchar(32),
   PrimaryExchange varchar(14),
   PutOrCall varchar(4),
   Quantity NUMERIC(19,2),
   QueryID int,
   QuoteSize NUMERIC(19,8),
   Reconciled int,
   RecycleDate date,
   ReferenceGroupID int,
   ReferenceOrderID int,
   RegNMSExemptCode varchar(2),
   RegNMSOptOutISO varchar(1),
   RejectedShares NUMERIC(19,2),
   RepNumber varchar(14),
   Rollup int,
   RootOrderID varchar(16),
   RouteFlag int,
   RouteText varchar(12),
   RouteType int,
   RuleType varchar(20),
   SSExemptCode int,
   SalesCredit varchar(14),
   SalesCreditAccount varchar(14),
   ScheduleCode varchar(5),
   SecurityID varchar(27),
   SecurityIDAsEntered varchar(26),
   SecurityIDSource varchar(9),
   SecurityRootID varchar(8),
   SecurityRootIDSource varchar(9),
   SecuritySubtype varchar(14),
   SecurityType varchar(14),
   ServerID varchar(2),
   SettlementCurrency varchar(4),
   SettlementCurrencyPrice NUMERIC(19,8),
   SettlementInstruction varchar(15),
   Side varchar(4),
   SoftCommission varchar(14),
   Solicitation int,
   SourceDesk varchar(10),
   SourceRegionCode varchar(5),
   SourceServiceName varchar(14),
   SourceServiceOrderID varchar(20),
   SourceServiceUser varchar(14),
   SourceUser varchar(14),
   SourceUserCC varchar(14),
   StampTax NUMERIC(19,8),
   State varchar(7),
   StlCurAveragePrice NUMERIC(19,8),
   StopPrice NUMERIC(19,8),
   StoppedTime timestamp,
   StrategyAccount varchar(29),
   StrategyCrossAccount varchar(29),
   StrikePrice NUMERIC(19,8),
   SwitchAccount varchar(14),
   TSXBypass varchar(1),
   TSXRegID varchar(2),
   Tactic varchar(9),
   TaxType varchar(24),
   TimeInForce varchar(14),
   TopTrade int,
   Tranche varchar(9),
   TransactionName varchar(4),
   TransactionNumber int,
   TransactionTimeStamp timestamp,
   UnderlyingSecurityID varchar(9),
   UniqueClientOrderID varchar(30),
   WSSAreaCode varchar(14),
   WaveID varchar(16),
   WaveMark varchar(1),
   WghtedSumAverageFXRate NUMERIC(19,8),
   WghtedSumAveragePrice NUMERIC(19,8),
   WghtedSumStlCurAveragePrice NUMERIC(19,8),
   Risk varchar(8),
   Rank int,
   AdvisoryBroker varchar(11),
   GlobalReferenceGroupID varchar(21),
   OrderTypeTag varchar(3),
   ExternalClientBookingTag varchar(19),
   OriginalLCDTag int,
   UnsolicitedOut varchar(1),
   PRIMARY KEY (OrderID)
);


CREATE TABLE  FillDetails 
(
   ACTReport varchar(7),
   AsOfTimestamp timestamp,
   BookStreetSide varchar(14),
   BookingEntity varchar(10),
   BookingOriginalFillID varchar(16),
   ClearingBroker varchar(10),
   Compressed int,
   CompressedFillID int,
   ContraBroker varchar(15),
   CounterpartyID varchar(12),
   CrossTradingAccount varchar(6),
   Exchange varchar(13),
   ExchangeTag varchar(20),
   ExchangeTradeDate timestamp,
   ExecutingBroker varchar(15),
   ExecutionCapacity varchar(16),
   ExecutionDesk varchar(8),
   ExecutionExchangeID varchar(30),
   ExecutionExchangeTimestamp timestamp,
   ExecutionID varchar(16) NOT NULL,
   ExecutionOriginUser varchar(14),
   ExecutionPrice NUMERIC(19,8),
   ExecQuantity NUMERIC(19,2),
   FXRate NUMERIC(19,8),
   FillTimestamp timestamp,
   InstanceID varchar(1),
   LateFill varchar(1),
   LateFlag varchar(15),
   LiquidityIndicator varchar(3),
   MarkupPrice NUMERIC(19,8),
   NBBOAsk NUMERIC(19,8),
   NBBOBid NUMERIC(19,8),
   OATSReport varchar(14),
   OrderOriginatorRegionCode varchar(5),
   OriginalExecutionID varchar(36),
   PTMLevy NUMERIC(19,8),
   RecycleDate date,
   RegNMSExemptCode varchar(2),
   RootFillID varchar(16),
   SSExemptCode int,
   SecurityID varchar(27),
   ServerID varchar(2),
   SettlementCurrencyPrice NUMERIC(19,8),
   Side varchar(4),
   StampTax NUMERIC(19,8),
   TagType int,
   PRIMARY KEY (ExecutionID)
);


CREATE TABLE  FillAllocations 
(
   ACTReportInfo1 varchar(50),
   AllocQuantity NUMERIC(19,2),
   AutoBustAllocation int,
   BackCancelCorrect varchar(1),
   BackOfficeFillID int,
   BookingTag int,
   BrokerFee NUMERIC(19,8),
   ChangedTimestamp timestamp,
   CumulativeQuantity NUMERIC(19,2),
   CustomerAccount varchar(14),
   DestinationRegionCode varchar(5),
   DestinationServiceName varchar(15),
   DestinationServiceSeqNum int,
   DestinationUserCC varchar(14),
   ExecutionID varchar(16),
   ExecutionUser varchar(14),
   FOBOFillTradeID varchar(25),
   FXForwardPoints NUMERIC(19,8),
   FillBookingState varchar(7),
   FillID varchar(16) NOT NULL,
   FillState varchar(6),
   GiveUp varchar(9),
   InstanceID varchar(1),
   OrderID varchar(16),
   ParentFillID varchar(16),
   ParentFillOrderID varchar(16),
   Reason int,
   ReasonCode varchar(4),
   SalesCreditAccount varchar(14),
   SourceRegionCode varchar(5),
   SourceServiceName varchar(14),
   SourceUserCC varchar(14),
   TransactionName varchar(4),
   TransactionNumber int,
   TransactionTimeStamp timestamp,
   UnAllocQuantity NUMERIC(19,2),
   UniqueClientFillID varchar(30),
   PRIMARY KEY (FillID)
);

CREATE INDEX INSTT ON  orders 
(
  InstanceID,
  TransactionNumber
);
CREATE INDEX PORD ON  orders  (ParentOrderID) ;
CREATE INDEX DTDSK ON  orders  (DestinationDesk) ;
CREATE INDEX SCDSK ON  orders  (SourceDesk) ;
CREATE INDEX ORDT ON  orders 
(
  OrderID,
  TransactionNumber
);
CREATE INDEX RORD ON  orders  (RootOrderID) ;

CREATE INDEX INST ON  FillDetails (InstanceID) ;
CREATE INDEX PFID ON  FillAllocations (ParentFillID) ;
CREATE INDEX FIDT ON  FillAllocations 
(
  FillID,
  TransactionNumber
);
CREATE INDEX ORD ON  FillAllocations (OrderID) ;
CREATE INDEX EXIDX ON  FillAllocations (ExecutionID) ;
CREATE INDEX ITNUM ON  FillAllocations 
(
  InstanceID,
  TransactionNumber
);
